require('webpack-icons-installer/font-awesome');

import "./style.scss"
import "./fonts/fonts.scss"
import "./content/standart_buttons/standart_buttons.scss"
import "./plugins/ripple/ripple.scss"
import "./plugins/ripple/ripple.js"
import "../node_modules/jquery/dist/jquery.min.js"
import "./content/standart_buttons/buttons.scss"
import "./content/arrow_buttons/arrow_buttons.scss"
import "./content/percentages/percentages.scss"
import "./content/percentages/percentages.js"
import "./plugins/easypiechart/jquery.easypiechart.js"
import "../node_modules/chart.js/dist/Chart.js"
import "./content/sliders/sliders.js"
import "./plugins/ui/jquery-ui.js"
import "./plugins/ui/jquery-ui.scss"
import "./content/sliders/sliders.scss"
import "./content/stages/stages.scss"
import "./content/stages/stages.js"
import "./content/form_elements/form_elements.scss"
import "./content/form_elements/form_elements.js"
import "./content/search/search.scss"
import "./content/search/search.js"